chore(ci): Automate pre-commit runs (#585)
This is an opinionated change, and to be very clear the opinion is mine.
Linters which can also do formatting _should not_ be allowed to break
CI. If there is a programmatically defined "right way" things should be
done and tooling can do it, no purpose is served in making a human rerun
a tool to apply that formatting.

Extend the `pre-commit` CI step so that it will commit (as
@aspect-marvin) any formatting changes and push them back to the branch.

The motivation for doing this isn't just my own annoyance with pushing
lint commits, but also so that PRs from @renovate-bot will trigger
updates to the Gazelle manifest (or other code) so that those PRs can
auto-merge.

---

### Changes are visible to end-users: no

### Test plan

N/A.

---------

Co-authored-by: aspect-marvin[bot] <marvin@aspect.build>

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -41,9 +41,32 @@ jobs:
 
   pre-commit:
     runs-on: ubuntu-latest
+    if: always()
     steps:
       - uses: actions/checkout@v4
+        with:
+          ref: ${{ github.head_ref }}
       - uses: pre-commit/action@v3.0.1
+        continue-on-error: true
+      - name: Send automated commit
+        run: |
+          if ! git diff --quiet; then
+            git config --local user.name "aspect-marvin[bot]"
+            git config --local user.email "<marvin@aspect.build>"
+            git add .
+            git commit --message="Pre-commit changes"
+
+            for backoff in 5 10 15 20 25 30 runout; do
+              if ! git push; then
+                sleep $backoff
+              elif [ "$backoff" = "runout" ]; then
+                echo "ERROR: Failed to push commits!" >&2
+                exit 1
+              else
+                break
+              fi
+            done
+          fi
 
   verify-bcr-patches:
     runs-on: ubuntu-latest
